// <auto-generated />
using System;
using AutomaticPaymentReminder.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomaticPaymentReminder.Infrastructure.Migrations
{
    [DbContext(typeof(AutoPayReminderDbContext))]
    partial class AutoPayReminderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutomaticPaymentReminder.Domain.Entites.Customers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CustomerNum")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AutomaticPaymentReminder.Domain.Entites.Payments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AutomaticPaymentReminder.Domain.Entites.SubscriptionTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTypes");
                });

            modelBuilder.Entity("AutomaticPaymentReminder.Domain.Entites.Subscriptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CustomerNum")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomersId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ServiceProvider")
                        .HasColumnType("longtext");

                    b.Property<int>("SubscriptionNum")
                        .HasColumnType("int");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomersId");

                    b.HasIndex("TypeId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AutomaticPaymentReminder.Domain.Entites.Payments", b =>
                {
                    b.HasOne("AutomaticPaymentReminder.Domain.Entites.Subscriptions", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("AutomaticPaymentReminder.Domain.Entites.Subscriptions", b =>
                {
                    b.HasOne("AutomaticPaymentReminder.Domain.Entites.Customers", "Customers")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomaticPaymentReminder.Domain.Entites.SubscriptionTypes", "Type")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AutomaticPaymentReminder.Domain.Entites.Customers", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("AutomaticPaymentReminder.Domain.Entites.SubscriptionTypes", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("AutomaticPaymentReminder.Domain.Entites.Subscriptions", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
